CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    STREET      TEXT    NOT NULL,
    STATE       TEXT    NOT NULL,
    COUNTRY     TEXT    NOT NULL,
    ZIPCODE     INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID  INTEGER NOT NULL REFERENCES COMPANY (ID) DEFAULT 0,
    NAME        TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL                         DEFAULT '',
    DESCRIPTION TEXT    NOT NULL                         DEFAULT ''
);


CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME     TEXT    NOT NULL,
    LAST_NAME      TEXT    NOT NULL,
    EMAIL          TEXT    NOT NULL,
    TITLE          TEXT    NOT NULL,
    COMPANY_ID     INTEGER NOT NULL REFERENCES COMPANY (ID),
    DEPARTMENT_ID  INTEGER NOT NULL REFERENCES DEPARTMENT (ID),
    WORK_PHONE     TEXT    NOT NULL DEFAULT '',
    WORK_EXTENSION INTEGER NOT NULL DEFAULT 0,
    MOBILE_PHONE   TEXT    NOT NULL DEFAULT '',
    COMMENTS       TEXT    NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS TICKET
(
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE                 TEXT     NOT NULL,
    STATUS                TEXT     NOT NULL,
    PRIORITY              TEXT     NOT NULL,
    CREATED_ON            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMPLOYEE_ID           INTEGER  NOT NULL REFERENCES EMPLOYEE (ID),
    LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMMENT
(
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKET_ID INTEGER  NOT NULL REFERENCES TICKET (ID),
    POST      TEXT     NOT NULL,
    POSTED_ON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EMAIL
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    HOST            TEXT    NOT NULL,
    PORT            TEXT    NOT NULL,
    STARTTLS        BOOLEAN NOT NULL DEFAULT FALSE,
    OVER_SSL_OR_TLS BOOLEAN NOT NULL DEFAULT FALSE,
    AUTHENTICATION  BOOLEAN NOT NULL DEFAULT FALSE,
    USERNAME        TEXT    NOT NULL,
    PASSWORD        TEXT    NOT NULL,
    FROM_ADDRESS    TEXT    NOT NULL,
    BCC_ADDRESS     TEXT    NOT NULL
);

INSERT INTO EMAIL (ID, HOST, PORT, STARTTLS, OVER_SSL_OR_TLS, AUTHENTICATION, USERNAME, PASSWORD, FROM_ADDRESS,
                   BCC_ADDRESS)
VALUES (0, '', '', FALSE, FALSE, FALSE, '', '', '', '');

CREATE TRIGGER IF NOT EXISTS EMAIL_NO_INSERT
    BEFORE INSERT
    ON EMAIL
    WHEN (SELECT COUNT(*)
          FROM EMAIL) >= 1
BEGIN
    SELECT RAISE(IGNORE);
END;

CREATE TABLE IF NOT EXISTS ALERT_SETTINGS
(
    ID                                INTEGER PRIMARY KEY DEFAULT 0,
    DISABLE_ALERTS                    BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_NOTIFICATIONS             BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_INFO_ALERTS               BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_ERROR_ALERTS              BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_CONFIRMATION_ALERTS       BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_WARNING_ALERTS            BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_INFO_NOTIFICATION         BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_ERROR_NOTIFICATION        BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_CONFIRMATION_NOTIFICATION BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_WARNING_NOTIFICATION      BOOLEAN NOT NULL    DEFAULT FALSE
);

INSERT OR IGNORE INTO ALERT_SETTINGS (ID)
VALUES (0);
CREATE TRIGGER IF NOT EXISTS ALERT_NO_INSERT
    BEFORE INSERT
    ON ALERT_SETTINGS
    WHEN (SELECT COUNT(*)
          FROM ALERT_SETTINGS) >= 1
BEGIN
    SELECT RAISE(IGNORE);
END;

INSERT INTO COMPANY (ID, NAME, DESCRIPTION, EMAIL, STREET, STATE, COUNTRY, ZIPCODE)
VALUES (0, 'All Companies', 'All companies selector.', 'N/A', 'N/A', 'N/A', 'N/A', 0);

INSERT INTO DEPARTMENT (ID, COMPANY_ID, NAME, EMAIL, DESCRIPTION)
VALUES (0, 0, 'All Departments', 'N/A', 'ALl department selector.');

