ALTER TABLE TICKET
    ADD COLUMN LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS NEW_TICKET
(
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE                 TEXT     NOT NULL,
    STATUS                TEXT     NOT NULL,
    PRIORITY              TEXT     NOT NULL,
    CREATED_ON            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMPLOYEE_ID           INTEGER  NOT NULL REFERENCES EMPLOYEE (ID),
    LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO NEW_TICKET(ID, TITLE, STATUS, PRIORITY, CREATED_ON, EMPLOYEE_ID, LAST_OPENED_TIMESTAMP)
SELECT ID,
       TITLE,
       STATUS,
       PRIORITY,
       substr(CREATED_ON, 7, 4) || '-' || substr(CREATED_ON, 1, 2) || '-' || substr(CREATED_ON, 4, 2) || ' 00:00:00.000' AS CREATED_ON,
       EMPLOYEE_ID,
       LAST_OPENED_TIMESTAMP
FROM TICKET;

DROP TABLE TICKET;

ALTER TABLE NEW_TICKET
    RENAME TO TICKET;

UPDATE SCHEMA_VERSION SET MINOR = 2 WHERE ID = 0;