ALTER TABLE TICKET
    ADD COLUMN LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TICKET
    ADD COLUMN ATTACHED_JOURNAL_ID INTEGER NOT NULL REFERENCES JOURNAL (ID) DEFAULT -1;


CREATE TABLE IF NOT EXISTS JOURNAL
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTE       TEXT NOT NULL,
    CREATED_ON TEXT NOT NULL
);

UPDATE main.SCHEMA_VERSION
SET MINOR = 1
WHERE ID = 0;