ALTER TABLE TICKET
    ADD COLUMN LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS JOURNAL
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTE       TEXT NOT NULL,
    CREATED_ON TEXT NOT NULL,
    ATTACHED_TICKET INTEGER NOT NULL REFERENCES TICKET(ID)
);

UPDATE main.SCHEMA_VERSION
SET MINOR = 1
WHERE ID = 0;