CREATE TABLE IF NOT EXISTS ALERT_SETTINGS
(
    ID                                INTEGER PRIMARY KEY DEFAULT 0,
    DISABLE_ALERTS                    BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_NOTIFICATIONS             BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_INFO_ALERTS               BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_ERROR_ALERTS              BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_CONFIRMATION_ALERTS       BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_WARNING_ALERTS            BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_INFO_NOTIFICATION         BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_ERROR_NOTIFICATION        BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_CONFIRMATION_NOTIFICATION BOOLEAN NOT NULL    DEFAULT FALSE,
    DISABLE_WARNING_NOTIFICATION      BOOLEAN NOT NULL    DEFAULT FALSE
);

INSERT OR IGNORE INTO ALERT_SETTINGS (ID) VALUES(0);

CREATE TRIGGER IF NOT EXISTS ALERT_NO_INSERT
    BEFORE INSERT
    ON ALERT_SETTINGS
    WHEN (SELECT COUNT(*)
          FROM ALERT_SETTINGS) >= 1
BEGIN
    SELECT RAISE(IGNORE);
END;


UPDATE SCHEMA_VERSION
SET MINOR = 3
WHERE ID = 0;
