CREATE TABLE IF NOT EXISTS PROFILE_PICTURE
(
    ID          INTEGER PRIMARY KEY,
    IMAGE_NAME  TEXT    NOT NULL,
    IMAGE       BLOB    NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL REFERENCES EMPLOYEE (ID)
);

CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    STREET      TEXT    NOT NULL,
    STATE       TEXT    NOT NULL,
    COUNTRY     TEXT    NOT NULL,
    ZIPCODE     INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID  INTEGER NOT NULL REFERENCES COMPANY (ID) DEFAULT 0,
    NAME        TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL                         DEFAULT '',
    DESCRIPTION TEXT    NOT NULL                         DEFAULT ''
);

INSERT INTO DEPARTMENT (NAME)
SELECT DEPARTMENT
FROM EMPLOYEE WHERE DEPARTMENT IS NOT NULL AND DEPARTMENT <> '';

ALTER TABLE EMPLOYEE
    DROP COLUMN DEPARTMENT;

ALTER TABLE EMPLOYEE
    ADD COLUMN COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (ID) DEFAULT -1;

ALTER TABLE EMPLOYEE
    ADD COLUMN DEPARTMENT_ID INTEGER NOT NULL REFERENCES DEPARTMENT (ID) DEFAULT -1;

ALTER TABLE EMPLOYEE
    ADD COLUMN PROFILE_PICTURE INTEGER NOT NULL REFERENCES PROFILE_PICTURE (ID) DEFAULT -1;

INSERT INTO COMPANY (ID, NAME, DESCRIPTION, EMAIL, STREET, STATE, COUNTRY, ZIPCODE)
    VALUES (0, 'All Companies', 'All companies selector.', 'N/A', 'N/A', 'N/A', 'N/A', 0);

INSERT INTO DEPARTMENT (ID, COMPANY_ID, NAME, EMAIL, DESCRIPTION)
    VALUES (0, 0, 'All Departments', 'N/A', 'ALl department selector.');

UPDATE SCHEMA_VERSION
SET MINOR = 4
WHERE ID = 0;