CREATE TABLE IF NOT EXISTS PROFILE_PICTURE
(
    ID          INTEGER PRIMARY KEY,
    IMAGE_NAME  TEXT    NOT NULL,
    IMAGE       BLOB    NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL REFERENCES EMPLOYEE (ID)
);

CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    STREET      TEXT    NOT NULL,
    STATE       TEXT    NOT NULL,
    COUNTRY     TEXT    NOT NULL,
    ZIPCODE     INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID  INTEGER NOT NULL REFERENCES COMPANY (ID),
    NAME        TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL
);

ALTER TABLE EMPLOYEE
    ADD COLUMN COMPANY_ID NOT NULL REFERENCES COMPANY (ID) DEFAULT -1;

ALTER TABLE EMPLOYEE
    ADD COLUMN DEPARTMENT_ID NOT NULL REFERENCES DEPARTMENT (ID) DEFAULT -1;

ALTER TABLE EMPLOYEE
    ADD COLUMN PROFILE_PICTURE NOT NULL REFERENCES PROFILE_PICTURE (ID) DEFAULT -1;



UPDATE SCHEMA_VERSION
SET MINOR = 4
WHERE ID = 0;