CREATE TABLE PROFILE_PICTURE
(
    ID          INTEGER PRIMARY KEY,
    IMAGE_NAME  TEXT    NOT NULL,
    IMAGE       BLOB    NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL REFERENCES EMPLOYEE (ID)
);

UPDATE SCHEMA_VERSION
SET MINOR = 4
WHERE ID = 0;