CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME  TEXT NOT NULL,
    EMAIL      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TICKET
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE      TEXT    NOT NULL,
    STATUS     TEXT    NOT NULL DEFAULT 'OPEN',
    PRIORITY   TEXT    NOT NULL DEFAULT 'LOW',
    CREATED_ON TEXT    NOT NULL,
    USER_ID    INTEGER NOT NULL REFERENCES EMPLOYEE (ID)
);