CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    STREET      TEXT    NOT NULL,
    STATE       TEXT    NOT NULL,
    COUNTRY     TEXT    NOT NULL,
    ZIPCODE     INTEGER NOT NULL
);

INSERT INTO COMPANY (ID, NAME, DESCRIPTION, EMAIL, STREET, STATE, COUNTRY, ZIPCODE)
VALUES (0, 'All Companies', 'All companies selector.', 'N/A', 'N/A', 'N/A', 'N/A', 0);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID  INTEGER NOT NULL REFERENCES COMPANY (ID) DEFAULT 0,
    NAME        TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL                         DEFAULT '',
    DESCRIPTION TEXT    NOT NULL                         DEFAULT ''
);


INSERT INTO DEPARTMENT (ID, COMPANY_ID, NAME, EMAIL, DESCRIPTION)
VALUES (0, 0, 'All Departments', 'N/A', 'ALl department selector.');

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME     TEXT    NOT NULL,
    LAST_NAME      TEXT    NOT NULL,
    EMAIL          TEXT    NOT NULL,
    TITLE          TEXT    NOT NULL,
    COMPANY_ID     INTEGER NOT NULL REFERENCES COMPANY (ID),
    DEPARTMENT_ID  INTEGER NOT NULL REFERENCES DEPARTMENT (ID),
    WORK_PHONE     TEXT    NOT NULL DEFAULT '',
    WORK_EXTENSION INTEGER NOT NULL DEFAULT 0,
    MOBILE_PHONE   TEXT    NOT NULL DEFAULT '',
    COMMENTS       TEXT    NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS TICKET
(
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE                 TEXT     NOT NULL,
    STATUS                TEXT     NOT NULL,
    PRIORITY              TEXT     NOT NULL,
    CREATED_ON            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMPLOYEE_ID           INTEGER  NOT NULL REFERENCES EMPLOYEE (ID),
    LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMMENT
(
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKET_ID INTEGER  NOT NULL REFERENCES TICKET (ID),
    POST      TEXT     NOT NULL,
    POSTED_ON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EMAIL
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    HOST            TEXT    NOT NULL,
    PORT            TEXT    NOT NULL,
    STARTTLS        BOOLEAN NOT NULL DEFAULT FALSE,
    OVER_SSL_OR_TLS BOOLEAN NOT NULL DEFAULT FALSE,
    AUTHENTICATION  BOOLEAN NOT NULL DEFAULT FALSE,
    USERNAME        TEXT    NOT NULL,
    PASSWORD        TEXT    NOT NULL,
    FROM_ADDRESS    TEXT    NOT NULL,
    BCC_ADDRESS     TEXT    NOT NULL,
    DEBUGGING       BOOLEAN NOT NULL DEFAULT FALSE
);
