CREATE TABLE IF NOT EXISTS COMPANY
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL,
    STREET      TEXT    NOT NULL,
    STATE       TEXT    NOT NULL,
    COUNTRY     TEXT    NOT NULL,
    ZIPCODE     INTEGER NOT NULL
);

INSERT INTO COMPANY (ID, NAME, DESCRIPTION, EMAIL, STREET, STATE, COUNTRY, ZIPCODE)
VALUES (0, 'All Companies', 'All companies selector.', 'N/A', 'N/A', 'N/A', 'N/A', 0);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID  INTEGER NOT NULL REFERENCES COMPANY (ID) DEFAULT 0,
    NAME        TEXT    NOT NULL,
    EMAIL       TEXT    NOT NULL                         DEFAULT '',
    DESCRIPTION TEXT    NOT NULL                         DEFAULT ''
);


INSERT INTO DEPARTMENT (ID, COMPANY_ID, NAME, EMAIL, DESCRIPTION)
VALUES (0, 0, 'All Departments', 'N/A', 'ALl department selector.');

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID                          INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME                  TEXT    NOT NULL,
    LAST_NAME                   TEXT    NOT NULL,
    EMAIL                       TEXT    NOT NULL,
    TITLE                       TEXT    NOT NULL,
    COMPANY_ID                  INTEGER NOT NULL REFERENCES COMPANY (ID),
    DEPARTMENT_ID               INTEGER NOT NULL REFERENCES DEPARTMENT (ID),
    WORK_PHONE                  TEXT    NOT NULL DEFAULT '',
    WORK_EXTENSION              INTEGER NOT NULL DEFAULT 0,
    MOBILE_PHONE                TEXT    NOT NULL DEFAULT '',
    COMMENTS                    TEXT    NOT NULL DEFAULT '',
    PREVENT_ACCIDENTAL_DELETION BOOLEAN NOT NULL DEFAULT TRUE,
    IS_DISABLED                 BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS TICKET_CATEGORIES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME"      TEXT NOT NULL,
    COLOR       TEXT NOT NULL DEFAULT '#5DADD5',
    DESCRIPTION TEXT NOT NULL DEFAULT ''
);

INSERT INTO TICKET_CATEGORIES (ID, NAME)
VALUES (0, 'DEFAULT');

CREATE TABLE IF NOT EXISTS TICKET
(
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE                 TEXT     NOT NULL,
    STATUS                TEXT     NOT NULL,
    PRIORITY              TEXT     NOT NULL,
    CREATED_ON            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_OPENED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CATEGORY_ID           INTEGER  NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TICKET_EMPLOYEE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKET_ID   INTEGER NOT NULL REFERENCES TICKET (ID),
    EMPLOYEE_ID INTEGER NOT NULL REFERENCES EMPLOYEE (ID)
);

CREATE TABLE IF NOT EXISTS COMMENT
(
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKET_ID INTEGER  NOT NULL REFERENCES TICKET (ID),
    POST      TEXT     NOT NULL,
    POSTED_ON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ALERTS
(
    ALERT_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    ALERT_NAME      TEXT    NOT NULL,
    ALERT_STATE     BOOLEAN NOT NULL DEFAULT TRUE,
    ALERT_PARENT_ID INTEGER NOT NULL
);

INSERT INTO ALERTS(ALERT_NAME, ALERT_STATE, ALERT_PARENT_ID)
VALUES ('DISABLE_ALERTS', FALSE, -1),
       ('DISABLE_NOTIFICATIONS', FALSE, -1),
       ('INFORMATIONAL_ALERTS', TRUE, 1),
       ('ERROR_ALERTS', TRUE, 1),
       ('CONFIRMATION_ALERTS', TRUE, 1),
       ('WARNING_ALERTS', TRUE, 1),
       ('INFORMATION_NOTIFICATIONS', TRUE, 2),
       ('ERROR_NOTIFICATIONS', TRUE, 2),
       ('CONFIRMATION_NOTIFICATIONS', TRUE, 2),
       ('WARNING_NOTIFICATIONS', TRUE, 2);

CREATE TABLE IF NOT EXISTS MODULE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL,
    STATE       BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO MODULE(NAME, DESCRIPTION, STATE)
VALUES ('URLs', 'Allows URLs to be attached to tickets.', true);

INSERT INTO MODULE(NAME, DESCRIPTION, STATE)
VALUES ('Documents', 'Allows documents to be attached to tickets.', true);

CREATE TABLE IF NOT EXISTS TICKET_LINK
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    TICKET_ID   INTEGER NOT NULL REFERENCES TICKET (ID),
    LINK        TEXT    NOT NULL,
    DESCRIPTION TEXT    NOT NULL
);