CREATE TABLE IF NOT EXISTS LINKED_TICKET
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TICKET_ID INTEGER NOT NULL REFERENCES TICKET(ID),
  LINKED_ID INTEGER NOT NULL REFERENCES TICKET(ID)
);

ALTER TABLE TICKET ADD COLUMN RESOLVED_BY DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00.0'
