CREATE TABLE IF NOT EXISTS LINKED_TICKET
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TICKET_ID INTEGER NOT NULL REFERENCES TICKET(ID),
  LINKED_ID INTEGER NOT NULL REFERENCES TICKET(ID)
);

ALTER TABLE TICKET ADD COLUMN RESOLVED_BY TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS TICKET_CATEGORIES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME"      TEXT NOT NULL,
    COLOR       TEXT NOT NULL DEFAULT '#5DADD5',
    DESCRIPTION TEXT NOT NULL DEFAULT ''
);

INSERT INTO TICKET_CATEGORIES (ID, NAME)
VALUES (0, 'DEFAULT');

ALTER TABLE TICKET
    ADD COLUMN CATEGORY_ID INT NOT NULL DEFAULT 0;